# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.1
mod_name = Better Slots
mod_id = better_slots
mod_description = A little mod that improves the inventory slot management.
mod_author = Alfakynz
mod_license = MIT
mod_website = https://github.com/Alfakynz/Better-Slots
maven_group = com.alfakynz.better-slots
archives_base_name = better-slots

# Minecraft properties
minecraft_version = 26.1

# Fabric
loader_version = 0.18.4
loom_version=1.15-SNAPSHOT

# Dependencies
clothconfig_version = 26.1.154
modmenu_version = 18.0.0-alpha.8